In [13]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [14]:
connection = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [19]:
arquivo = "z0019_2.csv"
data_ingestão = datetime.now()
df = pd.read_csv(f"../landing/{arquivo}", sep=";")
df['arquivo'] = arquivo
df['data_ingestão'] = data_ingestão

df

   NATBR    MAKTX WERKS  MAINS  LABST      arquivo              data_ingestão
0  10003    PREGO  BT10    100     60  z0019_2.csv 2026-05-23 20:30:10.387842
1  10004    SERRA  BT50    100    200  z0019_2.csv 2026-05-23 20:30:10.387842
2  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-05-23 20:30:10.387842

In [20]:
connection.execute("""

CREATE TABLE IF NOT EXISTS bronze_produto (
                   NATBR VARCHAR,
                   MAKTX VARCHAR,
                   WERKS VARCHAR,
                   MAINS VARCHAR,
                   LABST VARCHAR,     
                   arquivo VARCHAR,
                   data_ingestão TIMESTAMP
                )
""")

In [21]:
connection.execute("INSERT INTO bronze_produto select * from df")

In [22]:
result = connection.execute("SELECT * FROM bronze_produto").fetchdf()
result

   NATBR     MAKTX WERKS MAINS LABST      arquivo              data_ingestão
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-05-23 20:29:52.084393
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-05-23 20:29:52.084393
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-05-23 20:29:52.084393
3  10003     PREGO  BT10   100    60  z0019_2.csv 2026-05-23 20:30:10.387842
4  10004     SERRA  BT50   100   200  z0019_2.csv 2026-05-23 20:30:10.387842
5  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-05-23 20:30:10.387842

In [23]:
connection.execute("ALTER TABLE bronze_produto RENAME TO bronze_z0019")

In [24]:
connection.close()